# Generated by Django 3.2.9 on 2021-11-10 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeErrorApp',
            fields=[
                ('id_time_error', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end_app_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loginstanceapp',
            name='end_app_time',
        ),
        migrations.RemoveField(
            model_name='loginstanceapp',
            name='status',
        ),
        migrations.AddField(
            model_name='loginstanceapp',
            name='error_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logService.timeerrorapp'),
        ),
    ]
